
title: Haosen(Russell) Xing
url: ''
baseurl: '' #change it according to your repository name


# Profile information
yourname: Haosen(Russell) Xing  ## put your name
title: 'Email: haosenx (at) andrew dot cmu dot edu'  ## your title
location: Pittsburgh, PA


## Social Profiles
CV: https://docs.google.com/gview?url=https://github.com/RussellKsing/russellksing.github.io/raw/master/documents/cv_haosenx.pdf&embedded=true
github: http://github.com/RussellKsing
googlescholar: https://scholar.google.com/citations?user=n_xOx1MAAAAJ&hl=en
linkedin: http://linkedin.com/in/haosen-russell-xing-34b20375
## your linkedin account url

# Update all the sections by editing the files inside _includes folder.
